# Debian distribution to be installed in the filesystem image
DEBIAN_VERSION?=jessie

# Available space in the filesystem image, in MB
FS_SIZE?=2048

# Additional mkfs flags
MKFS_FLAGS?=

# Target architecture of the FS image. Valid values include:
# alpha amd64 arm armel hppa i386 ia64 mips mipsel powerpc s390 sparc
# However, note that it may not be possible to compile some tools from the
# source code if no suitable cross-architecture compiler is installed.
SUBARCH?=amd64

# URL of the Debian mirror to get packages from
DEBIAN_MIRROR?=http://ftp.fi.debian.org/debian

# Comma separated list of packages to be included in the base system install.
# This comes handy should the Debian distribution being installed have broken
# dependencies.
ADDITIONAL_PACKAGES=debconf-utils,locales

